"""actualizar_tablas_faltantes

Revision ID: 3b3024b538f4
Revises: d4e36f9a0b13
Create Date: 2026-04-15 22:29:08.539691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3024b538f4'
down_revision: Union[str, Sequence[str], None] = 'd4e36f9a0b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('police_consumptions', sa.Column('dinner_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('pricing_config', sa.Column('dinner_price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_config', 'dinner_price')
    op.drop_column('police_consumptions', 'dinner_price_snapshot')
    # ### end Alembic commands ###
