"""initial_schema

Revision ID: a1fa05e431bb
Revises: 
Create Date: 2026-04-11 20:55:02.267699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fa05e431bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('civilians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('id_code', sa.String(length=50), nullable=False),
    sa.Column('payment_mode', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', name='paymentmode'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_civilians_id'), 'civilians', ['id'], unique=False)
    op.create_index(op.f('ix_civilians_id_code'), 'civilians', ['id_code'], unique=True)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_type', sa.Enum('DAILY_MENU', 'EXTRA', name='menuitemtype'), nullable=False),
    sa.Column('is_price_editable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_table('police_officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('badge_code', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_police_officers_badge_code'), 'police_officers', ['badge_code'], unique=True)
    op.create_index(op.f('ix_police_officers_id'), 'police_officers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATOR', 'CASHIER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('civilian_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('civilian_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('has_breakfast', sa.Boolean(), nullable=False),
    sa.Column('has_lunch', sa.Boolean(), nullable=False),
    sa.Column('has_dinner', sa.Boolean(), nullable=False),
    sa.Column('extras_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['civilian_id'], ['civilians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_civilian_consumptions_civilian_id'), 'civilian_consumptions', ['civilian_id'], unique=False)
    op.create_index(op.f('ix_civilian_consumptions_date'), 'civilian_consumptions', ['date'], unique=False)
    op.create_index(op.f('ix_civilian_consumptions_id'), 'civilian_consumptions', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('CASH', 'TICKETS', name='paymenttype'), nullable=False),
    sa.Column('civilian_id', sa.Integer(), nullable=True),
    sa.Column('police_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['civilian_id'], ['civilians.id'], ),
    sa.ForeignKeyConstraint(['police_id'], ['police_officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_civilian_id'), 'payments', ['civilian_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_police_id'), 'payments', ['police_id'], unique=False)
    op.create_table('police_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('police_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('has_breakfast', sa.Boolean(), nullable=False),
    sa.Column('has_lunch', sa.Boolean(), nullable=False),
    sa.Column('has_dinner', sa.Boolean(), nullable=False),
    sa.Column('breakfast_tickets_used', sa.Integer(), nullable=False),
    sa.Column('lunch_tickets_used', sa.Integer(), nullable=False),
    sa.Column('breakfast_ticket_value_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lunch_ticket_value_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ticket_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_difference', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extras_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['police_id'], ['police_officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_police_consumptions_date'), 'police_consumptions', ['date'], unique=False)
    op.create_index(op.f('ix_police_consumptions_id'), 'police_consumptions', ['id'], unique=False)
    op.create_index(op.f('ix_police_consumptions_police_id'), 'police_consumptions', ['police_id'], unique=False)
    op.create_table('pricing_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_price_normal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('menu_price_2_meals', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('menu_price_3_meals', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('breakfast_ticket_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lunch_ticket_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dinner_ticket_equivalence', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_config_id'), 'pricing_config', ['id'], unique=False)
    op.create_table('extra_consumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=200), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('civilian_consumption_id', sa.Integer(), nullable=True),
    sa.Column('police_consumption_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['civilian_consumption_id'], ['civilian_consumptions.id'], ),
    sa.ForeignKeyConstraint(['police_consumption_id'], ['police_consumptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extra_consumptions_civilian_consumption_id'), 'extra_consumptions', ['civilian_consumption_id'], unique=False)
    op.create_index(op.f('ix_extra_consumptions_id'), 'extra_consumptions', ['id'], unique=False)
    op.create_index(op.f('ix_extra_consumptions_police_consumption_id'), 'extra_consumptions', ['police_consumption_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extra_consumptions_police_consumption_id'), table_name='extra_consumptions')
    op.drop_index(op.f('ix_extra_consumptions_id'), table_name='extra_consumptions')
    op.drop_index(op.f('ix_extra_consumptions_civilian_consumption_id'), table_name='extra_consumptions')
    op.drop_table('extra_consumptions')
    op.drop_index(op.f('ix_pricing_config_id'), table_name='pricing_config')
    op.drop_table('pricing_config')
    op.drop_index(op.f('ix_police_consumptions_police_id'), table_name='police_consumptions')
    op.drop_index(op.f('ix_police_consumptions_id'), table_name='police_consumptions')
    op.drop_index(op.f('ix_police_consumptions_date'), table_name='police_consumptions')
    op.drop_table('police_consumptions')
    op.drop_index(op.f('ix_payments_police_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_civilian_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_civilian_consumptions_id'), table_name='civilian_consumptions')
    op.drop_index(op.f('ix_civilian_consumptions_date'), table_name='civilian_consumptions')
    op.drop_index(op.f('ix_civilian_consumptions_civilian_id'), table_name='civilian_consumptions')
    op.drop_table('civilian_consumptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_police_officers_id'), table_name='police_officers')
    op.drop_index(op.f('ix_police_officers_badge_code'), table_name='police_officers')
    op.drop_table('police_officers')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_civilians_id_code'), table_name='civilians')
    op.drop_index(op.f('ix_civilians_id'), table_name='civilians')
    op.drop_table('civilians')
    # ### end Alembic commands ###
